
import { MenuItem, Review } from './types';

export const MENU_ITEMS: MenuItem[] = [
  // --- PAN PIZZA ---
  {
    id: 'pan1',
    name: 'Pan Onion',
    description: 'Delicious pan pizza with fresh Onion toppings.',
    variants: [{ label: 'Regular', price: 70 }],
    category: 'Veg Pizzas',
    subCategory: 'Pan Pizza',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'pan2',
    name: 'Pan Capsicum',
    description: 'Crispy pan pizza topped with fresh Capsicum.',
    variants: [{ label: 'Regular', price: 70 }],
    category: 'Veg Pizzas',
    subCategory: 'Pan Pizza',
    image: 'https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'pan3',
    name: 'Pan Corn',
    description: 'Sweet Corn pan pizza with golden kernels.',
    variants: [{ label: 'Regular', price: 80 }],
    category: 'Veg Pizzas',
    subCategory: 'Pan Pizza',
    image: 'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'pan4',
    name: 'Pan Paneer',
    description: 'Soft Paneer cubes on crispy pan pizza base.',
    variants: [{ label: 'Regular', price: 99 }],
    category: 'Veg Pizzas',
    subCategory: 'Pan Pizza',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=800',
  },

  // --- VEG PIZZAS (PAHADI SPECIAL) ---
  {
    id: 'p1',
    name: 'Pahadi Pizza',
    description: 'Our signature delight with Onion, Capsicum, Paneer, and rich Makhani Sauce.',
    variants: [{ label: 'Reg.', price: 100 }, { label: 'Med.', price: 200 }, { label: 'Lar.', price: 330 }],
    category: 'Veg Pizzas',
    subCategory: 'Pahadi Special',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800',
    isPopular: true,
  },

  // --- SIMPLE VEG PIZZAS ---
  {
    id: 'sv1',
    name: 'Margherita',
    description: 'The timeless classic with pure Pizza Sauce & Mozzarella Cheese.',
    variants: [{ label: 'Reg.', price: 89 }, { label: 'Med.', price: 179 }, { label: 'Lar.', price: 309 }],
    category: 'Veg Pizzas',
    subCategory: 'Simple Veg',
    image: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'sv2',
    name: 'Corn Cheese Pizza',
    description: 'Golden Sweet Corn kernels buried under a blanket of Mozzarella.',
    variants: [{ label: 'Reg.', price: 89 }, { label: 'Med.', price: 179 }, { label: 'Lar.', price: 309 }],
    category: 'Veg Pizzas',
    subCategory: 'Simple Veg',
    image: 'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&q=80&w=800',
  },

  // --- CLASSIC VEG ---
  {
    id: 'cv1',
    name: 'Farm House',
    description: 'Tomato, Onion, Capsicum, Mushroom.',
    variants: [{ label: 'Reg.', price: 159 }, { label: 'Med.', price: 309 }, { label: 'Lar.', price: 459 }],
    category: 'Veg Pizzas',
    subCategory: 'Classic Veg',
    image: 'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'cv2',
    name: 'Special Country',
    description: 'Tomato, Onion, Capsicum.',
    variants: [{ label: 'Reg.', price: 159 }, { label: 'Med.', price: 309 }, { label: 'Lar.', price: 459 }],
    category: 'Veg Pizzas',
    subCategory: 'Classic Veg',
    image: 'https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'cv3',
    name: 'Paneer Pizza',
    description: 'Onion, Paneer, Capsicum.',
    variants: [{ label: 'Reg.', price: 159 }, { label: 'Med.', price: 309 }, { label: 'Lar.', price: 459 }],
    category: 'Veg Pizzas',
    subCategory: 'Classic Veg',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'cv4',
    name: 'Veg Green',
    description: 'Green Chilli, Capsicum, Green Coriander, Onion.',
    variants: [{ label: 'Reg.', price: 159 }, { label: 'Med.', price: 309 }, { label: 'Lar.', price: 459 }],
    category: 'Veg Pizzas',
    subCategory: 'Classic Veg',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800',
  },

  // --- DIFFERENT SAUCES ---
  {
    id: 'ds1',
    name: 'Schezwan Pizza',
    description: 'Onion, Capsicum, Green Chilli, Schez, Schez Sauce, Jalapeno.',
    variants: [{ label: 'Reg.', price: 189 }, { label: 'Med.', price: 349 }, { label: 'Lar.', price: 489 }],
    category: 'Veg Pizzas',
    subCategory: 'Different Sauces',
    image: 'https://images.unsplash.com/photo-1593504049359-74330189a355?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'ds2',
    name: 'Salsa Mexican',
    description: 'Red Paprika, Onion, Capsicum, Jalapeno, Mexican Sauce.',
    variants: [{ label: 'Reg.', price: 189 }, { label: 'Med.', price: 349 }, { label: 'Lar.', price: 489 }],
    category: 'Veg Pizzas',
    subCategory: 'Different Sauces',
    image: 'https://images.unsplash.com/photo-1593504049359-74330189a355?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'ds3',
    name: 'Veg Tandoori',
    description: 'Paneer, Corn, Tandoori Sauce, Capsicum.',
    variants: [{ label: 'Reg.', price: 189 }, { label: 'Med.', price: 349 }, { label: 'Lar.', price: 489 }],
    category: 'Veg Pizzas',
    subCategory: 'Different Sauces',
    image: 'https://images.unsplash.com/photo-1564128442383-9201fcc714eb?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'ds4',
    name: 'Pizza Makhani',
    description: 'Onion, Capsicum, Paneer, Makhani Sauce.',
    variants: [{ label: 'Reg.', price: 189 }, { label: 'Med.', price: 349 }, { label: 'Lar.', price: 489 }],
    category: 'Veg Pizzas',
    subCategory: 'Different Sauces',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'ds5',
    name: 'Tango Spicy',
    description: 'Red Paprika, Olives, Corn, Jalapeno.',
    variants: [{ label: 'Reg.', price: 189 }, { label: 'Med.', price: 349 }, { label: 'Lar.', price: 489 }],
    category: 'Veg Pizzas',
    subCategory: 'Different Sauces',
    image: 'https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&q=80&w=800',
  },

  // --- VEG PIZZA ---
  {
    id: 'vd1',
    name: 'Veggie Deluxe',
    description: 'Mushroom, Onion, Capsicum, Paneer & Capsicum.',
    variants: [{ label: 'Reg.', price: 220 }, { label: 'Med.', price: 390 }, { label: 'Lar.', price: 570 }],
    category: 'Veg Pizzas',
    subCategory: 'Veg Pizza',
    image: 'https://images.unsplash.com/photo-1544982503-9f984c14501a?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'vd3',
    name: 'Loaded Veg',
    description: 'Olives, Jalapeno, Mushroom, Tomato, Corn.',
    variants: [{ label: 'Reg.', price: 220 }, { label: 'Med.', price: 390 }, { label: 'Lar.', price: 570 }],
    category: 'Veg Pizzas',
    subCategory: 'Veg Pizza',
    image: 'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'vd4',
    name: 'Veg Supreme',
    description: 'Corn, Tomato, Black Olives, Jalapeno, Onion, Mushroom, Capsicum, Extra Cheese.',
    variants: [{ label: 'Reg.', price: 220 }, { label: 'Med.', price: 390 }, { label: 'Lar.', price: 570 }],
    category: 'Veg Pizzas',
    subCategory: 'Veg Pizza',
    image: 'https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&q=80&w=800',
    isPopular: true,
  },

  // --- STARTERS ---
  {
    id: 'st1',
    name: 'Spicy Cheese Pockets',
    description: 'Deliciously crispy pockets stuffed with a spicy, gooey cheese center.',
    variants: [{ label: 'Portion', price: 90 }],
    category: 'Starters',
    image: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'st2',
    name: 'French Fries',
    description: 'Classic golden fries, salted to perfection.',
    variants: [{ label: 'Portion', price: 70 }],
    category: 'Starters',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&q=80&w=800',
  },

  // --- PASTA ---
  {
    id: 'pst1',
    name: 'White Sauce Pasta',
    description: 'Creamy, velvety white sauce pasta with Italian herbs.',
    variants: [{ label: 'Regular', price: 90 }],
    category: 'Pasta',
    image: 'https://i0.wp.com/aartimadan.com/wp-content/uploads/2020/07/White-Sauce-Pasta.jpg?w=1000&ssl=1',
  },
  {
    id: 'pst2',
    name: 'Red Sauce Pasta',
    description: 'Tangy and spicy tomato-based pasta tossed with fresh mountain herbs.',
    variants: [{ label: 'Regular', price: 110 }],
    category: 'Pasta',
    image: 'https://plus.unsplash.com/premium_photo-1664478288635-b9703a502393?q=80&w=2960&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },

  // --- BURGER ---
  {
    id: 'br1',
    name: 'Veg Burger',
    description: 'Crispy vegetable patty with fresh greens and creamy mayo.',
    variants: [{ label: 'Normal', price: 50 }, { label: 'Premium', price: 70 }],
    category: 'Burger',
    image: 'https://images.unsplash.com/photo-1571091655789-405eb7a3a3a8?q=80&w=2072&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    id: 'br2',
    name: 'Spicy Veg Burger',
    description: 'A zesty twist with spicy patty and hot sauce.',
    variants: [{ label: 'Normal', price: 60 }, { label: 'Premium', price: 80 }],
    category: 'Burger',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=800',
    isPopular: true,
  },

  // --- MOMO ---
  {
    id: 'mo1',
    name: 'Veg Momo',
    description: 'Classic steamed momos with mixed vegetable filling.',
    variants: [{ label: 'Half', price: 30 }, { label: 'Full', price: 60 }],
    category: 'Momo',
    image: 'https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'mo3',
    name: 'Paneer Momo',
    description: 'Succulent paneer stuffing in delicate hand-folded momo shells.',
    variants: [{ label: 'Half', price: 40 }, { label: 'Full', price: 80 }],
    category: 'Momo',
    image: 'https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?auto=format&fit=crop&q=80&w=800',
  },

  // --- CHOWMEIN ---
  {
    id: 'cw1',
    name: 'Veg Chowmein',
    description: 'Stir-fried noodles with crisp hill vegetables and savory sauces.',
    variants: [{ label: 'Half', price: 30 }, { label: 'Full', price: 60 }],
    category: 'Chowmein',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'cw2',
    name: 'Egg Chowmein',
    description: 'Perfectly tossed noodles with farm-fresh eggs and crunchy veggies.',
    variants: [{ label: 'Half', price: 40 }, { label: 'Full', price: 80 }],
    category: 'Chowmein',
    image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=800',
  },

  // --- SHAKE & LASSI ---
  {
    id: 'shb',
    name: 'Banana Shake',
    description: 'Creamy and energy-rich shake made with fresh bananas.',
    variants: [{ label: 'Glass', price: 30 }],
    category: 'Shake',
    image: 'https://plus.unsplash.com/premium_photo-1695035006295-d37b73003e27?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  },
  {
    id: 'sh1',
    name: 'Mango Shake',
    description: 'Deliciously thick mango shake made with real fruit pulp.',
    variants: [{ label: 'Glass', price: 30 }],
    category: 'Shake',
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'l1',
    name: 'Lassi',
    description: 'Traditional Punjabi-style refreshing sweet lassi.',
    variants: [{ label: 'Glass', price: 40 }],
    category: 'Shake',
    image: 'https://images.unsplash.com/photo-1692620609860-be6717812f71?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  }
];

export const REVIEWS: Review[] = [
  {
    id: 'r1',
    author: 'Rahul Sharma',
    rating: 5,
    comment: 'Best pizza in Kaladhungi! The Pahadi Pizza is a must-try. Authentic wood-fired feel.',
    date: '2 days ago',
  },
  {
    id: 'r2',
    author: 'Anjali Bisht',
    rating: 5,
    comment: 'The Paneer Momos and Veggie Deluxe pizza are incredible. Very professional service.',
    date: '1 week ago',
  },
  {
    id: 'r3',
    author: 'Sharad Saini',
    rating: 5,
    comment: 'Perfect crust and fresh toppings. Finally a premium pizza outlet in our town!',
    date: '3 weeks ago',
  },
  {
    id: 'r4',
    author: 'Priya Verma',
    rating: 5,
    comment: 'Amazing taste and quality! The Veg Supreme pizza is my favorite. Highly recommended!',
    date: '4 days ago',
  },
  {
    id: 'r5',
    author: 'Vikram Singh',
    rating: 5,
    comment: 'Great variety of pizzas. The Pan Paneer pizza is delicious and value for money.',
    date: '1 week ago',
  },
  {
    id: 'r6',
    author: 'Meera Joshi',
    rating: 5,
    comment: 'Excellent service and fresh ingredients. The Schezwan Pizza has the perfect spice level.',
    date: '5 days ago',
  },
  {
    id: 'r7',
    author: 'Amit Kumar',
    rating: 5,
    comment: 'Best pizza place in town! The Loaded Veg pizza is loaded with toppings. Love it!',
    date: '2 weeks ago',
  },
  {
    id: 'r8',
    author: 'Sneha Reddy',
    rating: 5,
    comment: 'The Farm House pizza is amazing! Fresh vegetables and perfect cheese. Will order again.',
    date: '6 days ago',
  },
  {
    id: 'r9',
    author: 'Rajesh Patel',
    rating: 5,
    comment: 'Quick delivery and hot pizzas. The Pizza Makhani has authentic taste. Great job!',
    date: '1 week ago',
  },
  {
    id: 'r10',
    author: 'Kavita Nair',
    rating: 5,
    comment: 'The Tango Spicy pizza is perfect for spice lovers. Great quality and taste!',
    date: '3 days ago',
  },
  {
    id: 'r11',
    author: 'Suresh Yadav',
    rating: 5,
    comment: 'Fantastic pizzas! The Classic Veg section has great options. Very satisfied!',
    date: '1 week ago',
  },
  {
    id: 'r12',
    author: 'Neha Gupta',
    rating: 5,
    comment: 'The Veg Tandoori pizza is unique and delicious. Great combination of flavors!',
    date: '4 days ago',
  },
  {
    id: 'r13',
    author: 'Manoj Tiwari',
    rating: 5,
    comment: 'Best pizza experience! The Salsa Mexican pizza is amazing. Highly recommend!',
    date: '2 weeks ago',
  },
  {
    id: 'r14',
    author: 'Sunita Devi',
    rating: 5,
    comment: 'Great taste and reasonable prices. The Pan Corn pizza is my kids favorite!',
    date: '5 days ago',
  },
  {
    id: 'r15',
    author: 'Arjun Mehta',
    rating: 5,
    comment: 'Excellent quality pizzas! The Veg Green pizza is fresh and flavorful. Love it!',
    date: '1 week ago',
  },
];

